# Define Some Variables For Convenience

set(PROJECT_SOURCES
	src/xboxmapper.cpp
)
set(PROJECT_INCLUDE_DIRS
	${LIBEVDEV_INCLUDE_DIRS}
	${LIBUDEV_INCLUDE_DIRS}
	${LIBSYSTEMD_INCLUDE_DIRS}
	$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
	$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)
set(PROJECT_LIBRARIES
	${LIBEVDEV_LIBRARIES}
	${LIBUDEV_LIBRARIES}
	${LIBSYSTEMD_LIBRARIES}
)

set(PROJECT_EXEC_NAME ${PROJECT_NAME})
set(PROJECT_LIB_NAME "lib${PROJECT_NAME}")
